apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mallocsnoop
resources:
  - daemonset.yaml
  - podmonitor.yaml
commonLabels:
  app.kubernetes.io/part-of: mallocsnoop
  app.kubernetes.io/component: mallocsnoop
  app.kubernetes.io/instance: mallocsnoop
  app.kubernetes.io/name: mallocsnoop
