apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mallocsnoop-podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mallocsnoop
      app.kubernetes.io/instance: mallocsnoop
      app.kubernetes.io/name: mallocsnoop
      app.kubernetes.io/part-of: mallocsnoop
  podMetricsEndpoints:
    - port: web
